version: '3.8'
services:
 db:
  image: mysql:8.0
  container_name: todo-mysql
  ports:
   - '3307:3306'
  environment:
   MYSQL_ROOT_PASSWORD: 'root_password'
   MYSQL_DATABASE: 'todo_db'
   MYSQL_USER: 'user'
   MYSQL_PASSWORD: 'password'
  volumes:
   - db_data:/var/lib/mysql

volumes:
 db_data:
