CREATE TABLE IF NOT EXISTS `todos` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `due_date` TIMESTAMP NULL,
    `status` ENUM('TODO_STATUS_UNSPECIFIED', 'TODO_STATUS_INCOMPLETE', 'TODO_STATUS_COMPLETED') NOT NULL DEFAULT 'TODO_STATUS_INCOMPLETE',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` TIMESTAMP NULL
) ENGINE=InnoDB; 
-- dataを定義するためのSQL文です。